CREATE TABLE IF NOT EXISTS customer_order (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    customer_name VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS logistics_info (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    company VARCHAR(64) NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    status VARCHAR(128) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS support_ticket (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ticket_no VARCHAR(32) NOT NULL UNIQUE,
    order_no VARCHAR(32),
    problem_description VARCHAR(500) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS tool_call_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trace_id VARCHAR(64),
    session_id VARCHAR(64) NOT NULL,
    tool_name VARCHAR(64) NOT NULL,
    request_summary VARCHAR(500),
    result_summary VARCHAR(1000),
    success BOOLEAN NOT NULL,
    cost_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE tool_call_log ADD COLUMN IF NOT EXISTS trace_id VARCHAR(64);
ALTER TABLE tool_call_log ADD COLUMN IF NOT EXISTS cost_ms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tool_call_log ADD COLUMN IF NOT EXISTS customer_id VARCHAR(64);

CREATE TABLE IF NOT EXISTS conversation_summary (
    session_id VARCHAR(64) PRIMARY KEY,
    summary VARCHAR(4000) NOT NULL,
    summarized_message_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    summary VARCHAR(4000) NOT NULL,
    summarized_message_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_conversation_memory_customer_session UNIQUE (customer_id, session_id)
);

INSERT INTO conversation_memory (customer_id, session_id, summary, summarized_message_count, updated_at)
SELECT legacy.session_id, legacy.session_id, legacy.summary, legacy.summarized_message_count, legacy.updated_at
FROM conversation_summary legacy
WHERE NOT EXISTS (
    SELECT 1 FROM conversation_memory current_memory
    WHERE current_memory.customer_id = legacy.session_id
      AND current_memory.session_id = legacy.session_id
);

CREATE INDEX IF NOT EXISTS idx_ticket_order_no ON support_ticket(order_no);
CREATE INDEX IF NOT EXISTS idx_tool_log_session ON tool_call_log(session_id);
CREATE INDEX IF NOT EXISTS idx_tool_log_trace ON tool_call_log(trace_id);
CREATE INDEX IF NOT EXISTS idx_tool_log_customer ON tool_call_log(customer_id);
